[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
chain_drm = "6CTtHe2u4robZvXvP1SbdhKrRvZzYszAurBD7wxMydji"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/xiangpi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
